import './globals.css'
import { Inter } from 'next/font/google'
import {Navbar,PNavbar} from "./components/Navbar.jsx"
import {Theme} from "./components/Provider.jsx"
import Footer from "./components/Footer.jsx"
// import {TopBanner} from "./components/Banner.jsx"
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="root-html">
      <body className={inter.className}>
        <Theme className="dark:bg-gray-900">
          <PNavbar/>
          {children}
          <Footer />
        </Theme>    
      </body>
    </html>
  )
}