import './globals.css';
import { Navbar, PNavbar } from "./components/Navbar.jsx";
import { Theme } from "./components/Provider.jsx";
import Footer from "./components/Footer.jsx";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="root-html">
      <head>
        {/* Include the Poppins font directly */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" />
      </head>
      <body>
        <Theme className="dark:bg-gray-900">
          <PNavbar />
          {children}
          <Footer />
        </Theme>    
      </body>
    </html>
  );
}
